### ISSUE TITLE
Create sections that produce tabs

### ISSUE THREAD

**Issue by bmbrands** [bmbrands/moodle-format_dynamictabs#1]
Filter on section names using syntax 

{icon} fa-bullhorn {/icon} {tab} Test 1 {/tab}

**Comment by gjb2048** [comment]
Thoughts:

1. Hidden sections may cause issues with actually seeing the contained modules.
2. With labels in a section for the tabs then the course format cannot read them because they are rendered by the course renderer.
3. It might be ok for the section name to be the tab name and click on it in the navigation / breadcrumb and take you directly to that tab.  The syntax can be translated for such by methods in the course format.

**Comment by gjb2048** [comment]
````
\{icon\}(.*?)\{\/icon\} *\{tab\}(.*?)\{\/tab\}
````

![2016-03-01 17_47_32-php live regex](https://cloud.githubusercontent.com/assets/1058419/13436160/d66783d8-dfd5-11e5-9474-e943fb16f7f2.png)

**Comment by gjb2048** [comment]
TODO:

I think we can manipulate this in lib.php

````
    public function extend_course_navigation($navigation, navigation_node $node) {
        global $PAGE;
        // if section is specified in course/view.php, make sure it is expanded in navigation
        if ($navigation->includesectionnum === false) {
            $selectedsection = optional_param('section', null, PARAM_INT);
            if ($selectedsection !== null && (!defined('AJAX_SCRIPT') || AJAX_SCRIPT == '0') &&
                    $PAGE->url->compare(new moodle_url('/course/view.php'), URL_MATCH_BASE)) {
                $navigation->includesectionnum = $selectedsection;
            }
        }

        // check if there are callbacks to extend course navigation
        parent::extend_course_navigation($navigation, $node);

        // We want to remove the general section if it is empty.
        $modinfo = get_fast_modinfo($this->get_course());
        $sections = $modinfo->get_sections();
        if (!isset($sections[0])) {
            // The general section is empty to find the navigation node for it we need to get its ID.
            $section = $modinfo->get_section_info(0);
            $generalsection = $node->get($section->id, navigation_node::TYPE_SECTION);
            if ($generalsection) {
                // We found the node - now remove it.
                $generalsection->remove();
            }
        }
    }
````

To show the tab name in the navigation when editing if desired.  Thoughts Bas?

**Comment by gjb2048** [comment]
Hi Bas,

This https://github.com/bmbrands/moodle-format_dynamictabs/commit/e6365d9ce3f8ee8ab12743d610200d4fea553148 gets the tab name from the section name if its in the correct format.

Can then build upon code for the icon etc.

Need to learn about tabtree etc.

What do you think of the solution so far navigation wise?

Cheers,

Gareth

**Comment by bmbrands** [comment]
Regex looks nice. There is a nice magic function to process strings like this:

<?php
class blabla() {

    public function process_section_name($name) {
        
        if (stripos($name, '{icon}') === false) {
            return false;
        }

        $regex = '|\{icon\}(.*?)\{\/icon\} \{tab\}(.*?)\{\/tab\}|Uis';
        $name = preg_replace_callback($regex, array($this, 'tabcontent'), $name);
    }

    private function tabcontent($matches) {
        $icon = $matches[1];
        $tabname = $matches[2];
        return '<div class="tabcontent">
                    <i class="fa fa-' . $icon . '">
                    <span class="tabname">' . $tabname . '</span>
                </div>';
    }
}

**Comment by gjb2048** [comment]
Interesting, I think the callback needs 'self::' prefix to give the it an instantiated object scope.

**Comment by gjb2048** [comment]
However, will be more complex and really need to keep as a string as mark-up can break course backups unless handled correctly: https://github.com/gjb2048/moodle-format_topcoll/blob/master/lib.php#L132-L134

**Comment by gjb2048** [comment]
Hi Bas,

Implemented in: https://github.com/bmbrands/moodle-format_dynamictabs/commit/aa5bef89d2fdd3c9916ca1f16b59561ce749151d.

Cheers,

Gareth
