### ISSUE TITLE
Learn tab icon

### ISSUE THREAD

**Issue by gjb2048** [bmbrands/moodle-format_dynamictabs#10]
Currently there is no icon.  The spec shows that there is one.  Should this be fixed or set-able by the user?  If the former then easy to code, if the latter then can be a course format setting.

In fact, 'Learn' is a language string.  Is this correct?

**Comment by bmbrands** [comment]
![screen shot 2016-03-10 at 19 18 14](https://cloud.githubusercontent.com/assets/491790/13679602/dec25a78-e6f4-11e5-95bd-bb84290aea22.png)

please hard code this one an add to learn tab

**Comment by gjb2048** [comment]
Implemented in: https://github.com/bmbrands/moodle-format_dynamictabs/commit/28ca992b65e6124754049dc236b75896f3338092 - also taken opportunity to centre and place icons above text as per the design: https://github.com/bmbrands/moodle-format_dynamictabs/commit/28ca992b65e6124754049dc236b75896f3338092#diff-4e7bb40584b55a44f4657b188986bff4R14
