### ISSUE TITLE
Course format not recognized on install.

### ISSUE THREAD

**Issue by bmbrands** [bmbrands/moodle-format_dynamictabs#11]
I had this weird issue:

I installed the course format to give it a go
I saw the plugin installer and everything seemed fine
After install My bootstrap CSS was no longer loading
I removed the course format and the CSS was back
I moved the course format back in again an now it is not on the list of available formats. Not in the course edit page and not in the plugins management page.
Any idea what's going on?

**Comment by gjb2048** [comment]
Hi Bas,

No.  Anything in the php log?  I'll try as soon as possible to reproduce in another clean Moodle install.

G

**Comment by bmbrands** [comment]
Oh wow found something interesting in the logs:

[Fri Mar 04 11:02:45.418322 2016] [:error] [pid 582] [client 127.0.0.1:57343] Debugging: Could not find a safe place to split at offset(s): 345201. Those were ignored. in \n* line 237 of /lib/csslib.php: call to debugging()\n* line 68 of /lib/csslib.php: call to css_chunk_by_selector_count()\n* line 188 of /theme/styles.php: call to css_store_css()\n, referer: http://boyle.fritz.box/moodle_30/

**Comment by gjb2048** [comment]
That's chunking for IE.  Which is called by the theme CSS serving mechanism.  Does it occur every time you do a Purge all caches?

**Comment by gjb2048** [comment]
Will look into it with your latest Bootstrap, just need to set-up a test installation.

**Comment by gjb2048** [comment]
Hi Bas,

Can replicate:

````
[04-Mar-2016 11:33:13 Europe/London] Debugging: Could not find a safe place to split at offset(s): 345160. Those were ignored. in 
* line 237 of \lib\csslib.php: call to debugging()
* line 68 of \lib\csslib.php: call to css_chunk_by_selector_count()
* line 188 of \theme\styles.php: call to css_store_css()
````

**Comment by gjb2048** [comment]
Ok.... investigating.  Only happens with TDM off.  Set TDM on and get site back.  Going to look at things and debug csslib.php to see if I can find the offset info.

**Comment by gjb2048** [comment]
Moodle is fragile!!!  And does not tell you the issue.

Bug in dynamictabs styles.css:

````
.dtabcontent .fa { color: inherit; )
````

should be:

````
.dtabcontent .fa { color: inherit; }
````

I'll fix after making some toast.
