### ISSUE TITLE
Warning on changing to dynamic tabs on a topics based course

### ISSUE THREAD

**Issue by bmbrands** [bmbrands/moodle-format_dynamictabs#12]
Warning: Invalid argument supplied for foreach() in /www/moodle_30/course/format/dynamictabs/renderer.php on line 235

**Comment by bmbrands** [comment]
I can show you on a hangout call

**Comment by gjb2048** [comment]
Fixed in: https://github.com/bmbrands/moodle-format_dynamictabs/commit/01cab119d0f49789e99f12a778ac3dcd6b9fdb34
