### ISSUE TITLE
Create Mustache renderer objects for the section navigation menu

### ISSUE THREAD

**Issue by bmbrands** [bmbrands/moodle-format_dynamictabs#13]
Create an Object to be used with Mustache templates

in a renderer file:
function used = 

return $this->render_from_template('form_dynamictabs/sectionnav', $template);

So what I need is the $template Object.

```
$template = new Object();
$template->navitems = array();
foreach ($section as $sec) {
      $mysection = new Object();
      $mysection->name = 'some name';
      $template->navitems[] = $mysection;
}
```

One of the navitems needs to be the active / current one.

**Comment by gjb2048** [comment]
Hi Bas,

Implemented in https://github.com/bmbrands/moodle-format_dynamictabs/commit/264a2d551bdc772651769a6491996bee4477fca9 and I've made some of the other code more efficient with one less call on the call stack.

Put in place basic styling and screen shots for info and some questions:

![2016-03-11 13_29_23-course_ dt section_ test 2](https://cloud.githubusercontent.com/assets/1058419/13703441/2e3f4ee6-e78e-11e5-9853-98508fe167f9.png)
![2016-03-11 13_28_43-course_ nodt](https://cloud.githubusercontent.com/assets/1058419/13703443/2e470d0c-e78e-11e5-97cb-d3917337df37.png)
![2016-03-11 13_33_12-course_ dt section_ test 2](https://cloud.githubusercontent.com/assets/1058419/13703442/2e4675c2-e78e-11e5-8959-833c05894538.png)

Cheers,

Gareth

**Comment by gjb2048** [comment]
Umm, I'll close to show that done as far as I can go.

**Comment by bmbrands** [comment]
Looks great, thanks!
