### ISSUE TITLE
Render tabs

### ISSUE THREAD

**Issue by bmbrands** [bmbrands/moodle-format_dynamictabs#2]
Name: from section
Link: from first activity in section
Icon: font-awesome / glypicon
Use core renderer for tabs

       
        foreach ($tabitems as $tab) {
            $link = new moodle_url('/local/catalogue/'. $tab. '.php');
            if ($linked == $tab) {
                $tabs[] = new tabobject($tab, $link, get_string($tab.'tab', 'local_catalogue'), '', true);
            } else {
                $tabs[] = new tabobject($tab, $link, get_string($tab.'tab', 'local_catalogue'));
            }
        }
        return $this->tabtree($tabs, $selected);

Highlight active tab

**Comment by bmbrands** [comment]
![screen shot 2016-03-01 at 14 31 27](https://cloud.githubusercontent.com/assets/491790/13428373/5080d29e-dfba-11e5-9958-e9263de926c2.png)

**Comment by gjb2048** [comment]
Hi Bas,

Implemented in https://github.com/bmbrands/moodle-format_dynamictabs/commit/aa5bef89d2fdd3c9916ca1f16b59561ce749151d etc.

Cheers,

Gareth

**Comment by gjb2048** [comment]
Using font-awesome only.  Are glyph-icons needed too?
