### ISSUE TITLE
Create code snippet that renders the tabs in a theme layout.

### ISSUE THREAD

**Issue by bmbrands** [bmbrands/moodle-format_dynamictabs#4]
Some that you can then just add to the theme layout file.

**Comment by gjb2048** [comment]
This should be along the lines of:

````
$formatrenderer = $PAGE->get_renderer('format_dynamictabs');
echo $formatrenderer->render_tabs();
````

**Comment by gjb2048** [comment]
Confirmed, code is:

`if ($PAGE->pagelayout == 'incourse') {
    $formatrenderer = $PAGE->get_renderer('format_dynamictabs');
    echo $formatrenderer->render_tabs();
}`
