### ISSUE TITLE
new clone of topics format

### ISSUE THREAD

**Issue by bmbrands** [bmbrands/moodle-format_dynamictabs#5]
call it dynamictabs
default to one per page

**Comment by gjb2048** [comment]
Moodle version?

**Comment by bmbrands** [comment]
Moodle 3.0

**Comment by gjb2048** [comment]
Ta :)

**Comment by gjb2048** [comment]
Note:  Leaving 'coursedisplay' setting in for the moment until decided not needed.

**Comment by gjb2048** [comment]
Topics renamed to Sections.
